[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "trading-bot-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "psycopg2-binary",
    "sqlalchemy",
    "pandas",
    "requests",
    "python-dotenv",
    "pykrakenapi",
    "pandas-ta",
    "pytz",
    "bcrypt",
    "pyjwt",
    "httpx" # Ensure this is still here
]
# Add this section:
packages = ["api", "core", "solar"] # Explicitly list your top-level packages
