name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Service container for PostgreSQL database
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    # --- Backend Setup ---
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure Python package discovery
      run: |
        echo '' >> services/pyproject.toml
        echo '[tool.setuptools.packages.find]' >> services/pyproject.toml
        echo 'where = ["."]' >> services/pyproject.toml
        echo 'include = ["api*", "core*", "solar*"]' >> services/pyproject.toml

    - name: Install backend dependencies
      working-directory: ./services
      run: pip install -e .

    # --- Frontend Setup ---
    - name: Set up Node.js and pnpm
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install frontend dependencies
      working-directory: ./app
      run: pnpm install

    # --- E2E Testing ---
    - name: Install Playwright test browsers
      working-directory: ./app
      run: pnpm playwright install --with-deps

    - name: Build the frontend
      working-directory: ./app
      run: pnpm run build

    - name: Run E2E tests with Playwright
      working-directory: ./app
      env:
        NEON_CONN_URL: "postgresql://user:password@localhost:5432/test_db"
      run: pnpm test:e2e

    # --- Upload Test Results (on failure) ---
    - name: Upload Playwright report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: app/playwright-report/
        retention-days: 7
