name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    # --- Backend Setup ---
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      # This relies on the corrected pyproject.toml in your repository
      run: pip install -e ./services

    # --- Frontend Setup ---
    - name: Set up Node.js and pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
        # Point to the correct lock file for caching
        cache-dependency-path: app/pnpm-lock.yaml

    - name: Install frontend dependencies
      run: pnpm install --frozen-lockfile
      working-directory: ./app

    # --- E2E Testing ---
    - name: Install Playwright browsers
      run: pnpm playwright install --with-deps
      working-directory: ./app

    - name: Build the frontend
      run: pnpm run build
      working-directory: ./app

    - name: Run end-to-end tests
      run: pnpm test:e2e
      working-directory: ./app
      env:
        # Use the connection string for the service container
        NEON_CONN_URL: "postgresql://user:password@localhost:5432/test_db"

    # --- Upload Test Results (on failure) ---
    - name: Upload Playwright report on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: app/playwright-report/
        retention-days: 7
